src/Entity/Cheque.php
<?php

namespace App\Entity;

use App\Repository\ChequeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ChequeRepository::class)]
class Cheque
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Montant is required")]
    #[Assert\Positive(message: "Montant must be positive")]
    private ?float $montantC = null;

    #[ORM\ManyToOne(inversedBy: 'cheques')]
    #[Assert\NotBlank(message: "User selection is required")]
    private ?User $destinationC = null;

    #[ORM\ManyToOne(inversedBy: 'cheques')]
    #[Assert\NotBlank(message: "compte owner selection is required")]
    private ?CompteClient $compteID = null;

     /* #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateEmission = null; */

    /**
 * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
 */
private ?\DateTimeInterface $DateEmission = null;

    #[ORM\OneToMany(mappedBy: 'chequeID', targetEntity: Reclamtion::class)]
    private Collection $reclamtions;

    #[ORM\Column]
    private ?int $isfav = null;

    public function __construct()
    {
        $this->reclamtions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
   

    public function getMontantC(): ?float
    {
        return $this->montantC;
    }

    public function setMontantC(float $montantC): static
    {
        $this->montantC = $montantC;

        return $this;
    }

    public function getDestinationC(): ?User
    {
        return $this->destinationC;
    }

    public function setDestinationC(?User $destinationC): static
    {
        $this->destinationC = $destinationC;

        return $this;
    }

    public function getCompteID(): ?CompteClient
    {
        return $this->compteID;
    }

    public function setCompteID(?CompteClient $compteID): static
    {
        $this->compteID = $compteID;

        return $this;
    }

    public function getDateEmission(): ?\DateTimeInterface
    {
        return $this->DateEmission;
    }

    public function setDateEmission(\DateTimeInterface $DateEmission): static
    {
        $this->DateEmission = $DateEmission;

        return $this;
    }

    /**
     * @return Collection<int, Reclamtion>
     */
    public function getReclamtions(): Collection
    {
        return $this->reclamtions;
    }

    public function addReclamtion(Reclamtion $reclamtion): static
    {
        if (!$this->reclamtions->contains($reclamtion)) {
            $this->reclamtions->add($reclamtion);
            $reclamtion->setChequeID($this);
        }

        return $this;
    }

    public function removeReclamtion(Reclamtion $reclamtion): static
    {
        if ($this->reclamtions->removeElement($reclamtion)) {
            // set the owning side to null (unless already changed)
            if ($reclamtion->getChequeID() === $this) {
                $reclamtion->setChequeID(null);
            }
        }

        return $this;
    }

    public function getIsfav(): ?int
    {
        return $this->isfav;
    }

    public function setIsfav(int $isfav): static
    {
        $this->isfav = $isfav;

        return $this;
    }
}

src/Form/ChequeType.php
<?php

namespace App\Form;

use App\Entity\Cheque;
use App\Entity\CompteClient;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType; 
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ChequeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('montantC')
            ->add('destinationC', ChoiceType::class, [
                'label' => 'Destination',
                'choices' => $this->getUserChoices(),
                'placeholder' => 'Select a User',
            ])
            ->add('compteID', ChoiceType::class, [
                'label' => 'Compte',
                'choices' => $this->getCompteChoices(), 
                'placeholder' => 'Select a Compte', 
               
            ])
           
          
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cheque::class,
        ]);
    }
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    
    private function getCompteChoices(): array
    {
        $compteRepository = $this->entityManager->getRepository(CompteClient::class);
        $comptes = $compteRepository->findAll();
        
        $choices = [];
        foreach ($comptes as $compte) { 
            $choices[$compte->getId()] = $compte; 
        }
    
        return $choices;
    }

    private function getUserChoices(): array
    {
        $userRepository = $this->entityManager->getRepository(User::class);
        $users = $userRepository->findAll();

        $choices = [];
        foreach ($users as $user) {
            $choices[ $user->getFullName()] = $user;
        }

        return $choices;
    }
}
    

src/Controller/BackController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Carte;
use Symfony\Component\Routing\Annotation\Route;

class BackController extends AbstractController
{
    #[Route('/back', name: 'app_back')]
    public function index(): Response
    {
        return $this->render('back/index.html.twig', [
            'controller_name' => 'BackController', 
        ]);
    }


}

src/Controller/ChequeController.php
<?php

namespace App\Controller;

use DateTimeImmutable; // Import DateTimeImmutable
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\ChequeRepository;
use App\Repository\ReclamtionRepository;
use App\Form\RecType;
use App\Form\Rec1Type;
use App\Form\Rec2Type;
use App\Form\ChequeType;
use App\Form\CheqType;
use App\Form\ReclamtionType;
use App\Entity\Cheque;
use App\Entity\Reclamtion;
use App\Entity\CompteClient;
use Symfony\Component\HttpFoundation\Request;
use Dompdf\Dompdf;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Address;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Form\FormError;
use Psr\Log\LoggerInterface;




use Dompdf\Options;


class ChequeController extends AbstractController
{  private $flashBag;

   
    private $logger;

    public function __construct(LoggerInterface $logger,FlashBagInterface $flashBag)
    {
        $this->logger = $logger;
        $this->flashBag = $flashBag;

    }

 

    #[Route('/cheques', name: 'cheque_list')]
    public function list(ChequeRepository $chequeRepository, ReclamtionRepository $ReclamtionRepository)
    {
        $cheques = $chequeRepository->findAll();
        $Reclamtions = $ReclamtionRepository->findAll();
        $randomNumber = mt_rand(1000, 9999);

        return $this->render("cheque/back/listcheques.html.twig", [
            "tabcheque" => $cheques,
            "tab" => $Reclamtions,
            'random' => $randomNumber,
        ]);
    }
    #[Route('/cheques/{ref}', name: 'cheque_list1')]                                                                   //front
    public function list1(ChequeRepository $chequeRepository, $ref, ReclamtionRepository $ReclamtionRepository)
    {
        $cheques = $chequeRepository->findByCompteID($ref);
        $Reclamtions = $ReclamtionRepository->findAll();
        $randomNumber = mt_rand(1000, 9999); // Generate a random number between 1000 and 9999




        return $this->render("cheque/front/list.html.twig", [
            "tabcheque" => $cheques,
            "tab" => $Reclamtions,
            "ref" => $ref,

            'random' => $randomNumber,
        ]);
    }

    #[Route('/cheques1/{ref}', name: 'cheque_list11')]
    public function list1111(ChequeRepository $chequeRepository, $ref, ReclamtionRepository $ReclamtionRepository, Request $request, ManagerRegistry $managerRegistry)
    {    
        if ($request->headers->get('content-type') === 'application/json' && $request->isMethod('POST')) {
            // Get the data sent via POST
            $data = json_decode($request->getContent(), true);
        
            // Log the received data for verification
            // Log the received data for verification
      $this->logger->info('Received data:', $data);

        
            // Assuming you're sending the isFav value via POST
            $isFav = $data['isFav'];
            $ID = $data['itemId'];
            var_dump($isFav);   
            
            $cheque = $chequeRepository->find($ID);
            $cheque->setIsfav($isFav);
            $entityManager = $managerRegistry->getManager();
        
            $entityManager->flush();
        
            return new JsonResponse(['success' => true]);
        }

      
    
        // If it's not an AJAX POST request, continue with the regular rendering logic
        $cheques = $chequeRepository-> findByCompteIDAndIsFav($ref);
        $Reclamtions = $ReclamtionRepository->findAll();
        $randomNumber = mt_rand(1000, 9999); // Generate a random number between 1000 and 9999
    
        return $this->render("cheque/front/listt.html.twig", [
            "tabcheque" => $cheques,
            "tab" => $Reclamtions,
            "ref" => $ref,
            'random' => $randomNumber,
        ]);
    }
    










    /**
     * @Route("/ajoutercheque", name="ajoutercheque")
     */
    public function ajoutercheque(Request $request, ManagerRegistry $managerRegistry): Response
    { 
        
        $cheque = new Cheque();
        $form = $this->createForm(ChequeType::class, $cheque);
        $randomNumber = mt_rand(1000, 9999);
       $cheque->setIsfav(0);
        $form->handleRequest($request);
        $entityManager = $managerRegistry->getManager();


        if ($form->isSubmitted() && $form->isValid()) {
           
          
            $entityManager->persist($cheque);
            $entityManager->flush();
            return $this->redirectToRoute('cheque_list');}
        

        return $this->render('cheque/back/index.html.twig', [
            'cheque' => $form->createView(),
            'random' => $randomNumber,
            
          
        ]);
    }
    /**
     * @Route("/addRec/{ref}", name="ajouterreclamtion1")
     */
    public function ajouterreclamtion1(Request $request, $ref, ManagerRegistry $managerRegistry, SessionInterface $session): Response
    {
        $reclamation = new Reclamtion();
        $entityManager = $managerRegistry->getManager();
        $ch = $entityManager->getRepository(Cheque::class)->find($ref);
        $randomNumber = mt_rand(1000, 9999);



        $form = $this->createForm(ReclamtionType::class, $reclamation);
        $reclamation->setChequeID($ch);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reclamation);
            $entityManager->flush();

            $REC1 = $session->get('REC1', []);
            $REC1[] = $reclamation;
            $session->set('REC1', $REC1);

            return $this->redirectToRoute('cheque_list');
        }

        return $this->render('cheque/back/AddRec.html.twig', [
            'reclamation' => $form->createView(),
            'random' => $randomNumber,

        ]);
    }
    /**
     * @Route("/addenc1/{ref}", name="ajouterreclamtion2")                                                   //front
     */
    public function ajouterreclamtion11(Request $request, $ref, ManagerRegistry $managerRegistry, SessionInterface $session): Response
    {
        $reclamtion = new reclamtion();
        $entityManager = $managerRegistry->getManager();
        $ch = $entityManager->getRepository(Cheque::class)->find($ref);


        $c = $ch->getCompteId();


        $form = $this->createForm(RecType::class, $reclamtion);
        $reclamtion->setChequeId($ch);
        $reclamtion->setStatutR('En cours');

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reclamtion);
            $entityManager->flush();

            $REC1 = $session->get('REC1', []);
            $REC1[] = $reclamtion;
            $session->set('REC1', $REC1);



            return $this->redirectToRoute('cheque_list1', ['ref' => $c->getId()]);
        }




        return $this->render('cheque/front/AddRe.html.twig', [
            'reclamtion' => $form->createView(),


        ]);
    }
    /**
     * @Route("/ajoutercheque1/{ref}", name="ajoutercheque1")                                                      //front
     */
    public function ajoutercheque1(Request $request, $ref, ManagerRegistry $managerRegistry): Response
    {
        $entityManager = $managerRegistry->getManager();
        
        // Find the compte by its ID
        $compte = $entityManager->getRepository(CompteClient::class)->find($ref);

        // Find all cheques related to the compte
        $cheques = $entityManager->getRepository(Cheque::class)->findByCompteID($ref);

        // Calculate the total sum of amounts of cheques
        $sommeCheques = 0;
        foreach ($cheques as $cheque) {
            $sommeCheques += $cheque->getMontantC();
        }

        // Create a new Cheque instance
        $cheque = new Cheque();
        $cheque->setCompteId($compte);
        $cheque->setIsfav(0);
        $cheque->setDateEmission(new DateTime());

        // Create the form
        $form = $this->createForm(CheqType::class, $cheque);

        // Handle the form submission
        $form->handleRequest($request);
        $diff=(($compte->getSolde()) - $sommeCheques);
        if($diff<0){$diff=0;}

        if ($form->isSubmitted() ) {
       
          
            if (($cheque->getMontantC()) > $diff) {
         
                // Set a custom error message directly on the form
                $form->get('montantC')->addError(new FormError('Insufficient balance. Please enter a lower amount.'));
            } else {
                // Persist and flush the new cheque
                $entityManager->persist($cheque);
                $entityManager->flush();

                // Redirect to the cheque list page
                return $this->redirectToRoute('cheque_list1', ['ref' => $ref]);
            }
        }

        // Render the form with or without error message
        return $this->render('cheque/front/addCheque.html.twig', [
            'cheque' => $form->createView(),
            'a' => $diff,
            's' => $sommeCheques,
       

        ]);
    }






    /**
     * @Route("/a2/{ref}", name="a1")
     */
    public function emptyRECTraitée1(SessionInterface $session, $ref, ManagerRegistry $managerRegistry): Response
    {

        $session->remove('RECTraitée');

        // Optionally, you can redirect the user to another page after emptying the array
        return $this->redirectToRoute('cheque_list1', ['ref' => $ref]);
    }
    /**
     * @Route("/a1", name="a2")
     */

templates/cheque/back/addRec.html.twig
{% extends 'backbase.html.twig' %}
{% block content %}
    <h1 style="color: #333; text-align: center;">Add a New reclamation</h1>
    <div style="max-width: 500px; margin: 0 auto;">
        {{ form_start(reclamation, {'attr': {'class': 'my-form' ,'novalidate': 'novalidate'}}) }}
        <div style="margin-bottom: 20px;">
            {{ form_widget(reclamation.categorie, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter categorie'}}) }}
        </div>
         {{ form_errors(reclamation.categorie) }} 
        <div style="margin-bottom: 20px;">
            {{ form_widget(reclamation.statutR, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter statutR'}}) }}
        </div>
           {{ form_errors(reclamation.statutR) }} 
        <div style="text-align: center;">
            <button type="submit" class="btn btn-primary btn-lg">Add</button>
        </div>
        {{ form_end(reclamation) }}
    </div>
{% endblock %}

templates/cheque/back/edit.html.twig
{% extends 'backbase.html.twig' %}
{% block content %}
    <h1 style="color: #333; text-align: center;">Modify the cheque</h1>
    <div style="max-width: 500px; margin: 0 auto;">
        {{ form_start(cheque, {'attr': {'class': 'my-form','novalidate': 'novalidate'}}) }}
        <div style="margin-bottom: 20px;">
            {{ form_widget(cheque.montantC, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter montantC'}}) }}
        </div>
          {{ form_errors(cheque.montantC) }} 
        <div style="margin-bottom: 20px;">
            {{ form_widget(cheque.destinationC , {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter destinationC'}}) }}
        </div>

         <div style="margin-bottom: 20px;">
            {{ form_widget(cheque.compteID, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter destinationC'}}) }}
        </div>

        <div style="text-align: center;">
            <button type="submit" class="btn btn-primary btn-lg">Modify</button>
        </div>
        {{ form_end(cheque) }}
    </div>
{% endblock %}

templates/cheque/back/editRec.html.twig
{% extends 'backbase.html.twig' %}

{% block content %}
<style>
    .response-input {
        height: 50px; /* Adjust the height as needed */
        font-size: 18px; /* Adjust the font size as needed */
    }
</style>
    <h1 style="color: #333; text-align: center;">Modify Reclamation</h1>
    <div style="max-width: 500px; margin: 0 auto;">
        {{ form_start(rec, {'attr': {'class': 'my-form','novalidate': 'novalidate'}}) }}
        <div style="margin-bottom: 20px;">
            {{ form_widget(rec.categorie, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter categorie'}}) }}
        </div>
        <div style="margin-bottom: 20px;">
            {{ form_widget(rec.statutR, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter statut'}}) }}
        </div>
        <!-- Additional input field for response type text grande -->
       <div style="margin-bottom: 20px;">
    <textarea id="response" name="response" class="form-control form-control-lg response-input" placeholder="Enter response" rows="6"></textarea>
        </div>
        <div style="text-align: center;">
            <button type="submit"  onclick="validateResponse()" class="btn btn-primary btn-lg">Modify</button>
        </div>
        {{ form_end(rec) }}
    </div>
 


{% endblock %}

templates/cheque/back/index.html.twig
{% extends 'backbase.html.twig' %}
{% block content %}
    <h1 style="color: #333; text-align: center;">Add the cheque</h1>
    <div style="max-width: 500px; margin: 0 auto;">
        {{ form_start(cheque, {'attr': {'class': 'my-form','novalidate': 'novalidate'}}) }}
        <div style="margin-bottom: 20px;">
            {{ form_widget(cheque.montantC, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter montant'}}) }}
        </div>
          {{ form_errors(cheque.montantC) }} 
          
        <div style="margin-bottom: 20px;">
            {{ form_widget(cheque.destinationC, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter destination'}}) }}
        </div>
                  {{ form_errors(cheque.destinationC) }} 


         <div style="margin-bottom: 20px;">
            {{ form_widget(cheque.compteID, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Enter CompteID'}}) }}
        </div>
                  {{ form_errors(cheque.compteID) }} 


      
       
        <div style="text-align: center;">
            <button type="submit" class="btn btn-primary btn-lg">Add</button>
        </div>
        {{ form_end(cheque) }}
    </div>
{% endblock %}

templates/cheque/back/listcheques.html.twig
{% extends 'backbase.html.twig' %}

{% block content %}

{% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
{% endfor %}
    <div class="container">
        <h2>Cheques List</h2>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="border: 1px solid black;">ID</th>
                        <th style="border: 1px solid black;">Montant</th>
                        <th style="border: 1px solid black;">Date Emission</th>
                        <th style="border: 1px solid black;">Destination</th>
                         <th style="border: 1px solid black;">CompteID</th>
                        <th style="border: 1px solid black;">Reclamations</th>
                        <th style="border: 1px solid black;" >Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cheque in tabcheque %}
                        <tr>
                            <td style="border: 1px solid black;">{{ cheque.id}}</td>
                            <td style="border: 1px solid black;" >{{ cheque.montantC }}</td>
                            <td style="border: 1px solid black;">{{ cheque.dateEmission|date }}</td>
                            <td style="border: 1px solid black;">{{ cheque.destinationC.getFullName() }}</td>
                            <td style="border: 1px solid black;">{{ cheque.compteID.getid() }}</td>
                            <td style="border: 1px solid black;">
                                <table border="1" style="border-color: black;" class="table table-bordered">
                                    <thead>
                                        <tr style="border: 1px solid black;">
                                            <th style="border: 1px solid black;">ID REC</th>
                                            <th style="border: 1px solid black;">categorie</th>
                                            <th style="border: 1px solid black;">Statut</th>
                                            <th style="border: 1px solid black;">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for enc in tab %}
                                            {% if enc.chequeID == cheque %}
                                                <tr>
                                                    <td style="border: 1px solid black;">{{ enc.id }}</td>
                                                    <td style="border: 1px solid black;">{{ enc.categorie }}</td>
                                                    
                                                    <td style="border: 1px solid black;">{{ enc.statutR }}</td>
                                                    <td style="border: 1px solid black;">
                                                        <a href="{{ path('reclamtion_remove', {'id': enc.id}) }}" class="btn btn-danger">Delete</a>
                                                        <a href="{{ path('rec_edit', {'ref': enc.id}) }}" class="btn btn-primary">Update</a>
                                                    </td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </td>
                            <td style="border: 1px solid black;">
                                <a href="{{ path('cheque_remove', {'id': cheque.id}) }}" class="btn btn-danger">Delete</a>
                                <a href="{{ path('ch_edit', {'ref': cheque.id}) }}" class="btn btn-primary">Update</a>
                                <a href="{{ path('ajouterreclamtion1', {'ref': cheque.id}) }}" class="btn btn-success">Add Reclamation</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{{ path('ajoutercheque') }}" class="btn btn-primary">Add Cheque</a>
    </div>
{% endblock %}